name: ssam-lite-server
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - bottleneck=1.3.2
  - ca-certificates=2021.7.5
  - certifi=2021.5.30
  - click=8.0.1
  - dataclasses=0.8
  - flask=1.1.2
  - importlib-metadata=4.8.1
  - intel-openmp=2021.3.0
  - itsdangerous=2.0.1
  - jinja2=3.0.1
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libllvm10=10.0.1
  - libstdcxx-ng=9.3.0
  - llvmlite=0.36.0
  - markupsafe=2.0.1
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - ncurses=6.2
  - numba=0.53.1
  - numexpr=2.7.3
  - numpy=1.20.3
  - numpy-base=1.20.3
  - openssl=1.1.1l
  - pandas=1.3.2
  - pip=21.2.4
  - python=3.9.7
  - python-dateutil=2.8.2
  - pytz=2021.1
  - readline=8.1
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.36.0
  - tbb=2020.3
  - tk=8.6.10
  - tzdata=2021a
  - werkzeug=2.0.1
  - wheel=0.37.0
  - xz=5.2.5
  - zipp=3.5.0
  - zlib=1.2.11

